services:
  server:
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - ATLAS_URI=${ATLAS_URI}
      - PORT=${PORT}
    depends_on:
      - mongo
  
  mongo:
    env_file:
      - .env.dev
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    
volumes:
  mongo-data:
