services:
  server:
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - ATLAS_URI=${ATLAS_URI}
      - PORT=${PORT}
    
